# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gpxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gpx/')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('position_of_distance', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('voice', models.FileField(upload_to='sound/')),
                ('voice_status', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
