# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_gpx_dataobj_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx_dataobj',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
