# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0004_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, null=True)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
